version: "2"

services:
  zookeeper:
    #TODO: Keep the version updated.
    image: docker.io/bitnami/zookeeper:3.7
    restart: always
    ports:
      # A standard ZooKeeper port is 2181.
      - "2181:2181"
    volumes:
      - type: bind
        # Path to the local (host) data folder.
        source: /media/username/disk_x/Docker/Kafka/m1/zookeeper_data
        target: /bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:2
    restart: always
    ports:
      # Port is non-standard to avoid collision with possible local
      # installation using the standard port 9092.
      - "9093:9093"
    volumes:
      - type: bind
        # Path to the local (host) data folder.
        source: /media/username/disk_x/Docker/Kafka/m1/kafka_data
        target: /bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
